### ISSUE TITLE
验证图识别模型如果是和那个引用的一模一样的，那么验证成功率应该很低吧，这个模型我拿知喵的图试过，角度差了有点多

### ISSUE THREAD

**Issue by liubo6324** [yuemiao-web/yuemiao_backend#1]

**Comment by liubo6324** [comment]
抢那种不是第一时间光的，有个思路，就是手动抢，通过改包把一些进去的按钮提前弄成可点击的，然后进去预约界面会快点

**Comment by coder-xiaotian** [comment]
旋转验证码，我还没在知苗上试过，因为知苗的旋转验证码是动态开启的。滑块验证码没什么问题，成功率还挺高

**Comment by coder-xiaotian** [comment]
> 抢那种不是第一时间光的，有个思路，就是手动抢，通过改包把一些进去的按钮提前弄成可点击的，然后进去预约界面会快点

那不如直接调那个接口就行了，提前拿到预约参数，到了时间就预约，但是这样可能容易被后台检测出来

**Comment by liubo6324** [comment]
我很久没分析那个，提前拿不到具体点疫苗的参数吧？提前进去连有苗的日期都加载不出来

**Comment by liubo6324** [comment]
滑块和旋转差很多，滑块我以前也试了直接cv2库识别缺口就过了时间还快，这个旋转，你随便知苗抢的点进去找个图下载下来测试，就知道这个模型是不行的了

**Comment by coder-xiaotian** [comment]
> 我很久没分析那个，提前拿不到具体点疫苗的参数吧？提前进去连有苗的日期都加载不出来

对，拿不到疫苗日期和时间，但是你说的改包也是为了让用户提前进入到选择日期那里刷新对吧？直接调接口刷新也行啊

**Comment by liubo6324** [comment]
不太懂，调用接口刷新后能显示到微信小程序里吗

**Comment by coder-xiaotian** [comment]
> 不太懂，调用接口刷新后能显示到微信小程序里吗

不会。我大概懂你意思，现在接口加密了，我说的那种走不通，反编译小程序包，改了再打成新包放到手机上，是这个意思吗？

**Comment by liubo6324** [comment]
改包是抓包改包的意思，把未到时间灰色的按钮激活而已，然后让用户手动抢，因为知苗服务器很渣，很多人第一步都会卡在进入接种点上

**Comment by liubo6324** [comment]
其实电脑端小程序好像就验证旋转图加了密

**Comment by coder-xiaotian** [comment]
> 改包是抓包改包的意思，把未到时间灰色的按钮激活而已，然后让用户手动抢，因为知苗服务器很渣，很多人第一步都会卡在进入接种点上

可以，可以试试

**Comment by coder-xiaotian** [comment]
> 其实电脑端小程序好像就验证旋转图加了密
旋转验证码没抓过包，我只知道获取时间的返回数据加密了

**Comment by xsxsm** [comment]
> > 其实电脑端小程序好像就验证旋转图加了密
> > 旋转验证码没抓过包，我只知道获取时间的返回数据加密了

作者说是因为AES加密了   所以怎么获取解密key

**Comment by liubo6324** [comment]
> > > 其实电脑端小程序好像就验证旋转图加了密
> > > 旋转验证码没抓过包，我只知道获取时间的返回数据加密了
> 
> 作者说是因为AES加密了 所以怎么获取解密key

这个模型过不了旋转，所以怎么抢？

**Comment by coder-xiaotian** [comment]
> > > > 其实电脑端小程序好像就验证旋转图加了密
> > > > 旋转验证码没抓过包，我只知道获取时间的返回数据加密了
> > 
> > 作者说是因为AES加密了 所以怎么获取解密key
> 
> 这个模型过不了旋转，所以怎么抢？

那只能找精确度高的模型去了，机器学习这块儿我不懂，不会改
