### ISSUE TITLE
前端查询疫苗访问的地址有问题

### ISSUE THREAD

**Issue by 965962591** [yuemiao-web/yuemiao_backend#4]
您好，分别将前端和后端运行起来，访问前端，查询疫苗无响应，查看了访问地址为本地地址，请问如何才能正确的运行？谢谢！

**Comment by 965962591** [comment]
![](https://s2.loli.net/2021/12/16/oXdpNRbk4GAsBnZ.png)

**Comment by coder-xiaotian** [comment]
> ![](https://camo.githubusercontent.com/6a7217be59522573947420e85bcf1c42b40226a2ea476bde717497cdda48ab96/68747470733a2f2f73322e6c6f6c692e6e65742f323032312f31322f31362f6f5864704e52626b34474173426e5a2e706e67)

看上去好像是后端没有启动好，你访问下后端地址 http://localhost:8000 看行不行

**Comment by 965962591** [comment]
![image](https://user-images.githubusercontent.com/34186275/146701674-9893caba-d2f9-45c2-8047-41d549ad176d.png)
![image](https://user-images.githubusercontent.com/34186275/146701712-070d1a9f-f99a-4896-bbbf-4660c9181e0e.png)
启动有点问题，我也不确定哪里有问题？

**Comment by coder-xiaotian** [comment]
> ![image](https://user-images.githubusercontent.com/34186275/146701674-9893caba-d2f9-45c2-8047-41d549ad176d.png) ![image](https://user-images.githubusercontent.com/34186275/146701712-070d1a9f-f99a-4896-bbbf-4660c9181e0e.png) 启动有点问题，我也不确定哪里有问题？

出现page not found说明后台是启动好的，你再看看前端的代理有没有配置对

**Comment by 965962591** [comment]
您好，如何判断前端代理配置是否正确？

**Comment by chengxxxx** [comment]
> ![image](https://user-images.githubusercontent.com/34186275/146701674-9893caba-d2f9-45c2-8047-41d549ad176d.png) ![image](https://user-images.githubusercontent.com/34186275/146701712-070d1a9f-f99a-4896-bbbf-4660c9181e0e.png) 启动有点问题，我也不确定哪里有问题？

我也是这个问题，您解决了吗

**Comment by coder-xiaotian** [comment]
> 
代理是在这里配置的
![image](https://user-images.githubusercontent.com/22257014/147474547-d8314be4-9b89-43ff-b00f-83dd96463ca8.png)

只要后台启动起来，http://localhost:8000能访问，哪怕是404也是没问题的，如果还有问题请加我qq：775146061

**Comment by coder-xiaotian** [comment]
> > ![image](https://user-images.githubusercontent.com/34186275/146701674-9893caba-d2f9-45c2-8047-41d549ad176d.png) ![image](https://user-images.githubusercontent.com/34186275/146701712-070d1a9f-f99a-4896-bbbf-4660c9181e0e.png) 启动有点问题，我也不确定哪里有问题？
> 
> 我也是这个问题，您解决了吗

同上
